export enum PartOfSpeech {
  NOUN = 'noun',
  VERB = 'verb',
  ADJECTIVE = 'adjective',
  ADVERB = 'adverb',
  PRONOUN = 'pronoun',
  PREPOSITION = 'preposition',
  CONJUNCTION = 'conjunction',
  INTERJECTION = 'interjection',
  DETERMINER = 'determiner',
  PHRASE = 'phrase',
  PHRASAL_VERB = 'phrasal_verb',
  COLLOCATION = 'collocation',
  IDIOM = 'idiom',
  SENTENCE_PATTERN = 'sentence_pattern',
}
